import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import { PT_Serif } from 'next/font/google';

const ptSerif = PT_Serif({
  weight: ['400', '700'], // Choix des poids disponibles
  style: ['normal', 'italic'], // Styles disponibles
  subsets: ['latin'],
  display: 'swap',
});

const playfairDisplay = Playfair_Display({
  weight: ['400', '700'], // Spécifiez les poids nécessaires
  style: ['normal', 'italic'], // Spécifiez les styles nécessaires
  subsets: ['latin'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={ptSerif.className}>
      <body>{children}</body>
    </html>
  );
}

